source 'https://rubygems.org'

#<struct Rails::Generators::AppBase::GemfileEntry name="rails", version="4.1.0", comment="Bundle edge Rails instead: gem 'rails', github: 'rails/rails'", options={}, commented_out=false>

gem 'rails'
gem 'rails-api'
gem 'sqlite3'

gem 'fabrication'
gem 'faker'
gem 'rabl-rails'
#<struct Rails::Generators::AppBase::GemfileEntry name="sqlite3", version=nil, comment="Use sqlite3 as the database for Active Record", options={}, commented_out=false>

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
